#!/usr/bin/env sh
if [ $# -ne 1 ]; then
  echo 'Usage:'
  echo 'JackAnalyzer source.jack'
  echo 'JackAnalyzer source_directory'
  exit 1
fi
binary_path=`dirname $0`
python ${binary_path}/src/jack_compiler/jack_compiler.py $@
