#!/usr/bin/env sh
if [ $# -ne 1 ]; then
  echo 'Usage:'
  echo 'VMTranslator source.vm'
  echo 'VMTranslator source_directory'
  exit 1
fi
binary_path=`dirname $0`
python ${binary_path}/src/vm_translator/vm_translator.py $@
